name: Build Test App

on: #推送到main分支会触发该工作流
  push:
    branches: [ main ]  
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Npm Install
        run: |
          npm ci

      - name: Build Dist
        env:
          TOKEN_SUYUAN: ${{ secrets.TOKEN_SUYUAN }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 溯元机械臂.exe
          path: dist/溯元机械臂*.exe
          retention-days: 1

  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'

  #     - name: Npm Install
  #       run: npm ci

  #     - name: Build Dist
  #       env:
  #         GA_ID: ${{ secrets.GA_ID }}
  #         NODE_ENV: production
  #         NODE_OPTIONS: --max_old_space_size=8192
  #         CSC_IDENTITY_AUTO_DISCOVERY: false
  #       run: npm run dist

  #     - name: Archive production artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: SuYuan-Desktop.dmg
  #         path: dist/SuYuan-Desktop*.dmg
  #         retention-days: 1

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Npm Install
        run: npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 溯元机械臂.deb
          path: dist/溯元机械臂*.deb
          retention-days: 1
